#!/usr/bin/env bash

# Scans for .svg files in the script directory and outputs icons.scss

# Get the directory of the script
DIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
OUT="$DIR/icons.scss"

APPEND_DIR="@/assets/img/icons/"

echo "/* This file is generated by generate-icons.sh */" > $OUT
echo "/*       Do not edit this file directly        */" >> $OUT
echo "" >> $OUT
echo ".icon-common {" >> $OUT
echo "    -webkit-mask-repeat: no-repeat;" >> $OUT
echo "    mask-repeat: no-repeat;" >> $OUT
echo "    width: 100%;" >> $OUT
echo "    height: 100%;" >> $OUT
echo "    -webkit-mask-position: center;" >> $OUT
echo "    mask-position: center;" >> $OUT
echo "}" >> $OUT
echo "" >> $OUT

# Get a list of all .svg files in the directory
for file in "$DIR"/*.svg
do
    # Get the file name without the extension
    filename=$(basename -- "$file")
    extension="${filename##*.}"
    filename="${filename%.*}"
    
    file_url="$APPEND_DIR$filename.$extension"
    
    echo "" >> $OUT
    echo "/* $filename.$extension */" >> $OUT
    echo ".icon-$filename {" >> $OUT
    echo "    @extend .icon-common;" >> $OUT
    echo "    -webkit-mask-image: url(\"$file_url\");" >> $OUT
    echo "    mask-image: url(\"$file_url\");" >> $OUT
    echo "}" >> $OUT
    echo "" >> $OUT
done
    
echo "/* End of generated file */" >> $OUT