name: Run unit tests

'on':
  push:
    branches:
      - main
      - dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - run: npm ci
        
      - name: Test with Firebase emulators
        # When https://github.com/firebase/firebase-tools/issues/5904 is fixed, use @master
        uses: w9jds/firebase-action@v11.30.0
        with:
          args: emulators:exec --only firestore,storage,auth 'npm test -- --detectOpenHandles'
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECHESS_WEB }}'
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
