name: Run unit tests

'on':
  push:
    branches:
      - main
      - dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Setup secrets
        run: |
          echo "VITE_RECHESS_FIREBASE_API_KEY=${{ secrets.RECHESS_FIREBASE_API_KEY }}" >> .config/.env.local
          
      - uses: jsdaniell/create-json@v1.2.2
        with:
          name: ".config/admin-key.json"
          json: ${{ secrets.ADMIN_KEY_JSON }}
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - run: npm install
      
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('**/firebase.json') }}
          restore-keys: |
            ${{ runner.os }}-firebase-emulators-
        
      - name: Test with Firebase emulators
        uses: w9jds/firebase-action@master
        with:
          args: emulators:exec --only firestore,storage,auth 'npm test'
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECHESS_WEB }}'
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
