name: Run unit tests

'on':
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Setup enviroment variables
        run: |
          echo "VITE_RECHESS_FIREBASE_API_KEY=${{ secrets.RECHESS_FIREBASE_API_KEY }}" >> .config/.env.local
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - run: npm install
        
      - name: Test with Firebase emulators
        uses: w9jds/firebase-action@master
        with:
          args: emulators:exec --only firestore,storage,auth 'npm test'
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECHESS_WEB }}'
